Document: qiskit-sdk-py
Title: Debian qiskit-sdk-py Manual
Author: <insert document author here>
Abstract: This manual describes what qiskit-sdk-py is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qiskit-sdk-py/qiskit-sdk-py.sgml.gz

Format: postscript
Files: /usr/share/doc/qiskit-sdk-py/qiskit-sdk-py.ps.gz

Format: text
Files: /usr/share/doc/qiskit-sdk-py/qiskit-sdk-py.text.gz

Format: HTML
Index: /usr/share/doc/qiskit-sdk-py/html/index.html
Files: /usr/share/doc/qiskit-sdk-py/html/*.html
